# Generated by Django 4.2.13 on 2024-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовк записи"),
                ),
                ("contetnt", models.TextField(verbose_name="Содержимое записи")),
                ("author", models.CharField(max_length=100, verbose_name="Имя автора")),
                (
                    "publicationDate",
                    models.DateTimeField(verbose_name="Дата публикации"),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
