# Generated by Django 4.2.13 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(
                blank=True, upload_to="image/%Y", verbose_name="Изображение"
            ),
        ),
    ]
