# Generated by Django 4.2.13 on 2024-05-09 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publicationDate",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публикации"
            ),
        ),
    ]
